accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),

]

receipts/urls.py
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    AccountListView,
    AccountCreateView,
    CategoryListView,
    CategoryCreateView,
)


urlpatterns = [
    path('', ReceiptListView.as_view(), name='home'),
    path('create/', ReceiptCreateView.as_view(), name='receipt_create'),
    path('accounts/', AccountListView.as_view(), name='account_list'),
    path('accounts/create/', AccountCreateView.as_view(), name='account_create'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('categories/create/', CategoryCreateView.as_view(), name='category_create')
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

# Create your models here.

USER_MODEL = settings.AUTH_USER_MODEL


class Receipt(models.Model):
    vendor = models.CharField(max_length=100)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField(null=True, blank=False)
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name='receipts',
        on_delete=models.CASCADE,
        null=True
    )
    category = models.ForeignKey(
        "Category",
        related_name="receipts",
        on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return str(self.purchaser) + "'s " + "receipt"


class Category(models.Model):
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name='categories',
        on_delete=models.CASCADE,
        null=True
    )
    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name='accounts',
        on_delete=models.CASCADE,
        null=True
    )
    def __str__(self):
        return self.name 

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password1')
            user = User.objects.create_user(username=username,password=password)
            user.save()
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm(request.POST)
    context = {'form': form}
    return render(request, 'registration/signup.html', context)



# WHAT I DID ABOVE WAS SLIGHTLY DIFFERENT FROM HR INSTRUCTIONS BELOW,I GOT ABOVE FROM
# https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html

# function signup(request)
#     if the request method is "POST", then
#         form = UserCreationForm(request.POST)
#         if the form is valid, then
#             username = the "username" value from the request.POST dictionary
#             password = the "password1" value from the request.POST dictionary
#             user = create a new user using username and password
#             save the user object
#             login the user with the request and user object
#             return a redirect to the "home" path
#     otherwise,
#         form = UserCreationForm(request.POST)
#     context = dictionary with key "form" and value form
#     return render with request, "registration/signup.html", and the context

receipts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from receipts.models import Receipt, Account, Category
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = 'receipts/list.html'

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(CreateView):
    model = Receipt
    template_name = 'receipts/create.html'
    fields = ['vendor', 'total', 'tax', 'date', 'category', 'account']
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class AccountListView(ListView):
    model = Account
    template_name = 'receipts/accounts/list.html'
    
    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(CreateView):
    model = Account
    template_name = 'receipts/accounts/create.html'
    fields = ['name', 'number']
    success_url = reverse_lazy('account_list')

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("account_list")   


class CategoryListView(ListView):
    model = Category
    template_name = 'receipts/categories/list.html'

    def get_queryset(self):
        return Category.objects.filter(owner=self.request.user)


class CategoryCreateView(CreateView):
    model = Category
    template_name = 'receipts/categories/create.html'
    fields = ['name']
    success_url = reverse_lazy('category_list')

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("category_list")   

    

receipts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My Receipts</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li>
            <a href="{% url 'home' %}">Receipts</a>
          </li>
          <li>
            <a href="{% url 'receipt_create' %}">Create Receipt</a>
          </li>
          <li>
            <a href="{% url 'account_list' %}">Accounts</a>
          </li>
          <li>
            <a href="{% url 'account_create' %}">Create Account</a>
          </li>
          <li>
            <a href="{% url 'category_list' %}">Categories</a>
          </li>
          <li>
            <a href="{% url 'category_create' %}">Create Category</a>
          </li>
          <li>
            <a href="{% url 'logout' %}">Logout</a>
          </li>
        </ul>
      </nav>
    </header>
    {% block content %} {% endblock content %}
  </body>
</html>

receipts/templates/receipts/accounts/create.html
{% extends 'base.html' %} {% block content%}

    <main>
      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <div>
          <button>Create</button>
        </div>
      </form>
    </main>
  </body>
</html>

{% endblock content %}

receipts/templates/receipts/accounts/list.html
{% extends 'base.html' %} {% block content %}

<main>
    <h1>Accounts <h1>
  <table>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Number of receipts</th>
    </tr>
    {% for list in account_list %}
    <tr>
      <td>{{list.name}}</td>
      <td>{{list.number}}</td>
      <td>{{list.receipts.all|length}}</td>
    </tr>
    {% endfor %}
  </table>
</main>

{% endblock content %}

receipts/templates/receipts/categories/create.html
{% extends 'base.html' %} {% block content%}

    <main>
      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <div>
          <button>Create</button>
        </div>
      </form>
    </main>
  </body>
</html>

{% endblock content %}

receipts/templates/receipts/categories/list.html
{% extends 'base.html' %} {% block content %}

<main>
    <h1>Expense Categories <h1>
  <table>
    <tr>
      <th>Name</th>
      <th>Number of receipts</th>
    </tr>
    {% for list in category_list %}
    <tr>
      <td>{{list.name}}</td>
      <td>{{list.receipts.all|length}}</td>
    </tr>
    {% endfor %}
  </table>
</main>

{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %} {% block content%}

    <main>
      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <div>
          <button>Create</button>
        </div>
      </form>
    </main>
  </body>
</html>

{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %} {% block content %}

<main>
    <h1> Receipts <h1>
  <table>
    <tr>
      <th>Vendor</th>
      <th>Total</th>
      <th>Tax</th>
      <th>Date</th>
      <th>Category</th>
      <th>Account</th>
    </tr>
    {% for list in receipt_list %}
    <tr>
      <td>{{list.vendor}}</td>
      <td>{{list.total}}</td>
      <td>{{list.tax}}</td>
      <td>{{list.date}}</td>
      <td>{{list.category}}</td>
      <td>{{list.account}}</td>
    </tr>
    {% endfor %}
  </table>
</main>

{% endblock content %}